apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: baldur-ts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baldur-ts
  template:
    metadata:
      name: baldur-ts
      labels:
        app: baldur-ts
    spec:
      containers:
        - name: baldur-ts
          image: rzingle/baldur-ts
