apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: baldur-deployment
spec:
  selector:
    matchLabels:
      app: baldur
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: baldur
    spec:
      serviceAccountName: finnr-sa
      securityContext:
        fsGroup: 1000
      containers:
      - name: baldur-ts
        image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "2048Mi"
