apiVersion: v1
kind: ServiceAccount
metadata:
  name: finnr-sa
  namespace: ci360
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::952478859445:role/eksctl-baldur-eks-addon-iamserviceaccount-ci-Role1-1PHEIJTBLHM67
