apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baldur-ebs-claim
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: baldur-ebs-pod
spec:
  initContainers:
  - name: volume-permissions-hack
    image: busybox
    command: ["/bin/chmod","-R","a+rw", "/install/citng/service/data"]
    volumeMounts:
    - name: data-volume
      mountPath: /install/citng/service/data
  containers:
  - name: baldur-ebs-app
    image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /install/citng/service/data
      name: data-volume
  nodeSelector:
    role: stateful
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: baldur-ebs-claim
