apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bts-replicaset
  labels:
    app: baldur-efs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baldur-efs-app
  template:
    metadata:
      labels:
        app: baldur-efs-app
    spec:
      containers:
      - name: baldur-efs-app
        image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/mkt-devops/mkt-tenant-splitter
          name: data-volume
      nodeSelector:
        role: stateful
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: efs-claim
