apiVersion: v1
kind: Pod
metadata:
  name: lenses
  labels:
    name: lenses
spec:
  containers:
  - name: lenses-runtime
    image: rzingle/baldur_lenses
    ports:
      - containerPort: 9991
    env:
      - name: LENSES_PORT
        value: "9991"
      - name: LENSES_JMX_PORT
        value: "9015"
      - name: LENSES_LICENSE_FILE
        value: /data/sas-license.json
      - name: LENSES_SECRET_FILE
        value: /data/security.conf
      - name: LENSES_STORGE_DIR
        value: /data/storage_dir
      - name: LENSES_KAFKA_BROKERS
        value: PLAINTEXT://kafkadev-kafka1.cidev.sas.us:9092,PLAINTEXT://kafkadev-kafka2.cidev.sas.us:9092,PLAINTEXT://kafkadev-kafka3.cidev.sas.us:9092,PLAINTEXT://kafkadev-kafka4.cidev.sas.us:9092,PLAINTEXT://kafkadev-kafka5.cidev.sas.us:9092
      - name: LENSES_KAFKA_METRICS_DEFAULT_PORT
        value: "9393"
      - name: LENSES_ZOOKEEPER_HOSTS
        value: |
          [
            {url:"kafkadev-zookeeper1.cidev.sas.us:2181", metrics:{url:"kafkadev-zookeeper1.cidev.sas.us:9394", type:"JMX"}},
            {url:"kafkadev-zookeeper2.cidev.sas.us:2181", metrics:{url:"kafkadev-zookeeper2.cidev.sas.us:9394", type:"JMX"}},
            {url:"kafkadev-zookeeper3.cidev.sas.us:2181", metrics:{url:"kafkadev-zookeeper3.cidev.sas.us:9394", type:"JMX"}}
          ]
      - name: LENSES_SCHEMA_REGISTRY_URLS
        value: |
          [
            {url: "http://kafkadev-connect1.cidev.sas.us:8081", metrics:{url:"kafkadev-connect1.cidev.sas.us:9391", type:"JMX"}},
            {url: "http://kafkadev-connect2.cidev.sas.us:8081", metrics:{url:"kafkadev-connect2.cidev.sas.us:9391", type:"JMX"}},
            {url: "http://kafkadev-connect3.cidev.sas.us:8081", metrics:{url:"kafkadev-connect3.cidev.sas.us:9391", type:"JMX"}}
          ]
      - name: LENSES_KAFKA_CONNECT_CLUSTERS
        value: |
          [
            {
              name: "dev",
              urls: [
                {url:"http://kafkadev-connect1.cidev.sas.us:8083", metrics:{url:"kafkadev-connect1.cidev.sas.us:9392", type:"JMX"}},
                {url:"http://kafkadev-connect2.cidev.sas.us:8083", metrics:{url:"kafkadev-connect2.cidev.sas.us:9392", type:"JMX"}},
                {url:"http://kafkadev-connect3.cidev.sas.us:8083", metrics:{url:"kafkadev-connect3.cidev.sas.us:9392", type:"JMX"}}
              ],
              statuses: "connect-status",
              configs: "connect-configs",
              offsets: "connect-offsets"
            }
          ]
      - name: LENSES_SECURITY_MODE
        value: BASIC
      - name: LENSES_HEAP_OPTS
        value: "-Xmx1G"
    resources:
      requests:
        memory: "750Mi"
      limits:
        memory: "1.2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: lenses
spec:
  type: NodePort
  ports:
    - port: 9991
  selector:
    name: lenses
