apiVersion: v1
kind: Pod
metadata:
  name: baldur-ghost
spec:
  containers:
  - name: ghost
    image: ghost
    resources:
        requests:
            cpu: "500m"
            memory: "128Mi"
        limits:
            cpu: "1000m"
            memory: "256Mi"
