apiVersion: v1
kind: Pod
metadata:
  name: baldur-tensplit
spec:
  volumes:
    - name: "master-data"
  containers:
  - name: baldur-cname
    image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
    resources:
        requests:
            cpu: "500m"
            memory: "256Mi"
        limits:
            cpu: "1000m"
            memory: "1024Mi"
