apiVersion: v1
kind: Service
metadata:
  name: tensplit-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "sg-06fbb55190b56b931"
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: baldur
  type: LoadBalancer
