apiVersion: v1
kind: Pod
metadata:
  name: baldur-tensplit
spec:
  containers:
  - name: baldurpod
    image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
