apiVersion: v1
kind: Pod
metadata:
  name: baldur-tensplit
spec:
  containers:
  - name: baldurpod
    image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:baldur
    livenessProbe:
      httpGet:
        path: /tenantSplitter/commons/ping
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /tenantSplitter/commons/healthcheck
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
