apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baldur-pv-claim
  annotations:
    #volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
