##############################################################################
# Shared Configuration for Development and Production
##############################################################################

spring:
  profiles:
    active: development

# context root for actuator endpoints
management:
  context-path: /commons
  
# Kafka Stuff
kafka:
  cluster: 10.240.25.26:19092,10.240.25.29:19092
  schema-registry: http://10.240.28.237:8081
  ssl-required: true
  client-auth-required: true
  connect-distributed: 10.240.25.26:8085,10.240.25.29:8085
  certificate-store-rootname: dev
  keystore-store-password: Go4thsas
  keystore-key-password: Go4thsas
  truststore-store-password: Go4thsas
  
---
##############################################################################
# Development
# export SPRING_PROFILES_ACTIVE=development
##############################################################################
spring:
  profiles: development
  # enable H2 console (available at /h2-console - user: sa, password: <blank>)
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true

# general spring and config stuff
main:
  banner-mode: console
server:
  port: 8000
logging:
  level:
    root: WARN

# Application Specific stuff

# amazon suite
amazon:
  amazonID: baldur1
  url: www.amazon.com
  password: somewhatsecretstuff

#book stuff
books:
  isbn: 9783538065437
  default.category: fiction
  
---
##############################################################################
# Production
# export SPRING_PROFILES_ACTIVE=production
##############################################################################
spring:
  profiles: production
  
# Database (url is host:port/database)
  datasource:
    url: jdbc:postgresql://localhost:5432/baldur
    username: habuma
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  
# general spring and config stuff
main:
  banner-mode: off
server:
  port: 8000
logging:
  level:
    root: INFO

# Application Specific stuff

# amazon suite
amazon:
  amazonID: prodamondu
  url: www.amazon.com
  password: supersecretstuff

#book stuff
books:
  isbn: 9783538065437
  default.category: fiction
