# Shared Configuration for Development and Production

# context root for actuator endpoints
management:
  context-path: /commons
---
##############################################################################
# Development
# export SPRING_PROFILES_ACTIVE=development
##############################################################################
spring:
  profiles: development
  # enable H2 console (available at /h2-console - user: sa, password: <blank>)
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true

# general spring and config stuff
main:
  banner-mode: console
server:
  port: 8000
logging:
  level:
    root: WARN

# Application Specific stuff

# amazon suite
amazon:
  amazonID: baldur1
  url: www.amazon.com
  password: somewhatsecretstuff

#book stuff
books:
  isbn: 9783538065437
  default.category: fiction
  
---
##############################################################################
# Production
# export SPRING_PROFILES_ACTIVE=production
##############################################################################
spring:
  profiles: production
  
# Database (url is host:port/database)
  datasource:
    url: jdbc:postgresql://localhost:5432/baldur
    username: habuma
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  
# general spring and config stuff
main:
  banner-mode: off
server:
  port: 8000
logging:
  level:
    root: INFO

# Application Specific stuff

# amazon suite
amazon:
  amazonID: prodamondu
  url: www.amazon.com
  password: supersecretstuff

#book stuff
books:
  isbn: 9783538065437
  default.category: fiction
