apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: baldur-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baldur-tensplit
  template:
    metadata:
      labels:
        app: baldur-tensplit
    spec:
      containers:
      - name: baldur
        image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:mymir
