apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baldur-ebs-claim
  annotations:
    name: baldur-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: ebs-gp2-ext4
