kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp2-ext4
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4
