apiVersion: v1
kind: Pod
metadata:
  name: baldur-efs-pod
spec:
  initContainers:
  containers:
  - name: baldur-efs-app
    image: 952478859445.dkr.ecr.us-east-1.amazonaws.com/mkt-devops/mkt-tenant-splitter:mymir
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: efs-claim
